# Generated by Django 2.2.5 on 2019-12-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Course_Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(max_length=100, verbose_name='课程知识点')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程知识点表',
                'verbose_name_plural': '课程知识点表',
                'db_table': 'Course_Knowledge',
            },
        ),
        migrations.CreateModel(
            name='Course_Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100, verbose_name='课程题目')),
                ('scoresum', models.IntegerField(default=0, verbose_name='题目总分')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程题目表',
                'verbose_name_plural': '课程题目表',
                'db_table': 'Course_Problem',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100, verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Student_Course_Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='学生题目分数')),
                ('course_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Course_Problem', verbose_name='课程题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生题目表',
                'verbose_name_plural': '学生题目表',
                'db_table': 'Student_Course_Problem',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course_problem',
            field=models.ManyToManyField(through='scores.Student_Course_Problem', to='scores.Course_Problem', verbose_name='学生题目分数'),
        ),
        migrations.CreateModel(
            name='Problem_Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Course_Knowledge', verbose_name='课程知识点')),
                ('course_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Course_Problem', verbose_name='课程题目')),
            ],
            options={
                'verbose_name': '题目知识点表',
                'verbose_name_plural': '题目知识点表',
                'db_table': 'Problem_Knowledge',
            },
        ),
        migrations.AddField(
            model_name='course_knowledge',
            name='course_problem',
            field=models.ManyToManyField(through='scores.Problem_Knowledge', to='scores.Course_Problem', verbose_name='题目对应知识点'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Teacher', verbose_name='教师'),
        ),
    ]
