# Generated by Django 2.2.5 on 2019-12-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_teacher_newpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='truename',
            field=models.CharField(max_length=100, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
