# Generated by Django 2.2.5 on 2019-12-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20191218_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_knowledge',
            name='course_problem',
        ),
        migrations.AddField(
            model_name='course_problem',
            name='course_knowledge',
            field=models.ManyToManyField(through='scores.Problem_Knowledge', to='scores.Course_Knowledge', verbose_name='题目对应知识点'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='newpassword',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='新密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='truename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名'),
        ),
    ]
