# Generated by Django 2.2.5 on 2019-12-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20191219_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('teacher', 'name')},
        ),
    ]
