# Generated by Django 2.2.5 on 2019-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20191223_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_knowledge',
            name='knowledge_detail',
            field=models.TextField(default='', verbose_name='知识点内容'),
        ),
        migrations.AddField(
            model_name='course_problem',
            name='problem_detail',
            field=models.TextField(default='', verbose_name='题目内容'),
        ),
    ]
