# Generated by Django 2.2.5 on 2019-12-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20191223_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=100, unique=True, verbose_name='学号'),
        ),
        migrations.AlterUniqueTogether(
            name='course_knowledge',
            unique_together={('course', 'knowledge')},
        ),
        migrations.AlterUniqueTogether(
            name='course_problem',
            unique_together={('course', 'problem')},
        ),
    ]
