# Generated by Django 2.2.5 on 2019-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20191225_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别'),
        ),
    ]
